;do $System.OBJ.LoadDir("/opt/irisapp/src","ck",,1)

zn "%SYS"
Do ##class(Security.Users).UnExpireUserPasswords("*")
zpm "load https://github.com/SergeyMi37/zapm.git"
zpm "load https://github.com/SergeyMi37/gateway-sql"

zapm "newdb https://github.com/SergeyMi37/DevBox.git"
zapm "newdb https://github.com/intersystems-community/webterminal"
zapm "newdb https://github.com/evshvarov/iris-cron-task"
zapm "newdb https://github.com/rcemper/oex-mapping"
https://github.com/SergeyMi37/gateway-sql
zn "USER"
zpm "load /opt/irisapp/ -v":1

zn "%SYS"
zpm "load https://github.com/SergeyMi37/isc-passwordless.git"
halt
